In [12]:
import pandas as pd
import os

In [13]:
m_n = 939565.421 # keV
m_p = 938272.089 # keV
df = pd.read_csv('BE_A_from_NuDat3.csv')
df.head()

   z  n  a name   BE_A_keV  BE_A_unc_keV
0  0  1  1    n     0.0000        0.0000
1  1  0  1    H     0.0000        0.0000
2  2  2  4   He  7073.9156        0.0002
3  3  3  6   Li  5332.3312        0.0003
4  3  4  7   Li  5606.4401        0.0006

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   z             52 non-null     int64
 1   n             52 non-null     int64
 2   a             52 non-null     int64
 3   name          52 non-null     object
 4   BE_A_keV      52 non-null     float64
 5   BE_A_unc_keV  52 non-null     float64
dtypes: float64(2), int64(3), object(1)
memory usage: 2.6+ KB

In [15]:
df['Mass_MeV'] = (df['z']*m_p + df['n']*m_n - df['BE_A_keV']*(df['z'] + df['n']))/1e3
df.to_csv('BE_A_from_NuDat3.csv', index=False)
df

     z   n   a name   BE_A_keV  BE_A_unc_keV      Mass_MeV
0    0   1   1    n     0.0000        0.0000    939.565421
1    1   0   1    H     0.0000        0.0000    938.272089
2    2   2   4   He  7073.9156        0.0002   3727.379358
3    3   3   6   Li  5332.3312        0.0003   5601.518543
4    3   4   7   Li  5606.4401        0.0006   6533.832870
5    4   5   9   Be  6462.6693        0.0085   8392.751437
6    5   5  10    B  6475.0835        0.0015   9324.436715
7    5   6  11    B  6927.7323        0.0011  10252.547916
8    6   6  12    C  7680.1446        0.0002  11174.863325
9    6   7  13    C  7469.8495        0.0002  12109.482437
10   7   7  14    N  7475.6148        0.0002  13040.203963
11   7   8  15    N  7699.4603        0.0002  13968.936086
12   8   8  16    O  7976.2072        0.0002  14895.080765
13   8   9  17    O  7750.7291        0.0002  15830.503106
14   8  10  18    O  7767.0981        0.0002  16762.023156
15   9  10  19    F  7779.0192        0.0002  17692.301646
16  11  12  23   Na  8111.4936        0.0002  21409.213678
17  13  14  27   Al  8331.5533        0.0018  25126.501112
18  14  14  28   Si  8447.7445        0.0002  26053.188294
19  14  15  29   Si  8448.6361        0.0002  26984.280114
20  14  16  30   Si  8520.6549        0.0008  27913.236335
21   5   2   7    B  3558.7055        3.5929   6545.580349
22   5   3   8    B  4717.1551        0.1250   7472.319467
23   5   4   9    B  6257.0713        0.1003   8393.308487
24   6   4  10    C  6032.0426        0.0070   9327.573792
25   7   4  11    N  5358.4023        0.4546  10267.223882
26   7   5  12    N  6170.1100        0.0833  11191.690408
27   7   6  13    N  7238.8634        0.0207  12111.191925
28   8   5  13    O  5811.7636        0.7328  12128.450890
29   8   6  14    O  7052.2783        0.0018  13044.837342
30   8   7  15    O  7463.6915        0.0327  13971.179286
31   9   6  15    F  6497.4597        0.9333  13984.379431
32   9   7  16    F  6964.0490        0.3353  14909.981964
33   9   8  17    F  7542.3284        0.0146  15832.752586
34   9   9  18    F  7631.6383        0.0257  16763.168101
35  10   7  17   Ne  6640.4991        0.0208  15846.790352
36  10   8  18   Ne  7341.2577        0.0202  16767.101619
37  10   9  19   Ne  7567.3431        0.0084  17695.030160
38  10  10  20   Ne  8032.2412        0.0002  18617.730276
39  10  11  21   Ne  7971.7136        0.0018  19550.534535
40  10  12  22   Ne  8080.4656        0.0008  20479.735699
41  11   9  20   Na  7298.5028        0.0554  18631.111712
42  11  11  22   Na  7915.6624        0.0060  20482.068037
43  13  11  24   Al  7649.5806        0.0095  22349.166854
44  13  13  26   Al  8149.7653        0.0026  24199.993732
45  14  17  31   Si  8458.2916        0.0014  28846.214363
46  15  15  30    P  8353.5064        0.0022  27916.957458
47  15  16  31    P  8481.1677        0.0002  28844.211872
48  16  15  31    S  8281.8013        0.0074  28849.098899
49  16  16  32    S  8493.1301        0.0002  29773.619997
50  16  17  33    S  8497.6304        0.0002  30704.543778
51  16  18  34    S  8583.4986        0.0013  31632.692050